version: '3.8'

services:
  metrics:
    build: .
    container_name: metrics
    ports:
      - "8080:8080"
    networks:
      - monitoring
    environment:
      - HTTP_ADDR=localhost
      - HTTP_PORT=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090" # UI prometheus
    networks:
      - monitoring
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" # UI grafana
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana_data:

networks:
  monitoring:
    driver: bridge